# Generated by Django 3.1.7 on 2021-03-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='maximum_discount',
            field=models.FloatField(null=True),
        ),
    ]
